# stage 1: build react app
FROM node:latest as build

WORKDIR /app

COPY package*.json ./

RUN npm install --silent

COPY ./ ./

RUN npm run build 

#stage 2: serve nginx

FROM nginx:latest

COPY --from=build /app/build /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
