services:
  server:
    build: 
      context: ./backend
      dockerfile: dockerfile.backend
    
    ports:
      - "5000:5000"
    networks:
      - mern
  
  client:
    build: 
      context: ./frontend
      dockerfile: dockerfile.frontend
    ports:
      - "3000:80"
    networks:
      - mern
  
networks:
  mern:
    driver: bridge