services:
  server:
    build: 
      context: ./backend
      dockerfile: dockerfile.backend
    
    ports:
      - "5000:5000"
    networks:
      - mern
    image: letungduong1624/sharre-server:0.0.1
  
  client:
    build: 
      context: ./frontend
      dockerfile: dockerfile.frontend
    ports:
      - "3000:80"
    networks:
      - mern
    image: letungduong1624/sharre-client:0.0.1

  
networks:
  mern:
    driver: bridge